version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      DATABESE_USER: ${DATABESE_PASSWORD}
      DATABESE_PASSWORD: ${DATABESE_USER}
      DATABESE_DB: ${DATABESE_DB}
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - services-networks

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - services-networks

  # api:
  #   build: .
  #   ports:
  #     - 3001:3001
  #   expose:
  #     - 3001
  #   volumes:
  #     - .:/usr/src/server
  #   env_file:
  #     - .env
  #   environment:
  #     DATABASE_HOST: ${DATABASE_HOST}
  #     DATABASE_PORT: ${DATABASE_PORT}
  #     DATABASE_USER: ${DATABASE_USER}
  #     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  #     DATABASE_DB: ${DATABASE_DB}
  #     SERVICE_NAME: nodeappservice
  #     SERVER_PORT: 3001
  #   depends_on:
  #     - db
  #   networks:
  #     - services-networks

volumes:
  db: {}

networks:
  services-networks:
    driver: bridge
